In [73]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model


In [74]:
df= pd.read_csv('/Users/ajagadis/Downloads/personal/hiring.csv')

In [75]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         NaN                    8.0                           9      50000
1         NaN                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    NaN                           7      72000
7        11.0                    7.0                           8      80000

In [76]:
df.experience=df.experience.fillna(0)

In [77]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         0.0                    8.0                           9      50000
1         0.0                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    NaN                           7      72000
7        11.0                    7.0                           8      80000

In [78]:
df_test_score1=df['test_score(out of 10)'].median()

In [79]:
df_test_score1

8.0

In [80]:
df['test_score(out of 10)']=df['test_score(out of 10)'].fillna(df_test_score1)

In [81]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         0.0                    8.0                           9      50000
1         0.0                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    8.0                           7      72000
7        11.0                    7.0                           8      80000

In [82]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   experience                  8 non-null      float64
 1   test_score(out of 10)       8 non-null      float64
 2   interview_score(out of 10)  8 non-null      int64  
 3   salary($)                   8 non-null      int64  
dtypes: float64(2), int64(2)
memory usage: 384.0 bytes


In [83]:
df.describe()

experience  test_score(out of 10)  interview_score(out of 10)  \
count     8.00000               8.000000                    8.000000   
mean      4.75000               7.875000                    7.875000   
std       4.26782               1.246423                    1.642081   
min       0.00000               6.000000                    6.000000   
25%       1.50000               7.000000                    6.750000   
50%       4.00000               8.000000                    7.500000   
75%       7.75000               8.250000                    9.250000   
max      11.00000              10.000000                   10.000000   

         salary($)  
count      8.00000  
mean   63000.00000  
std    11501.55269  
min    45000.00000  
25%    57500.00000  
50%    63500.00000  
75%    70500.00000  
max    80000.00000

In [86]:
reg=linear_model.LinearRegression()
reg.fit(df[['experience','test_score(out of 10)','interview_score(out of 10)']],df['salary($)'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [89]:
reg.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [92]:
reg.intercept_

17737.26346433771

In [94]:
reg.predict([[12,10,10]])

array([92002.18340611])

In [95]:
reg.predict([[2,9,6]])

array([53205.96797671])